/**
 * GOVERNMENT SENIOR SECONDARY SCHOOL 52 LNP
 * Data Fixtures & Localization Dictionary (English & Hindi)
 */

window.SCHOOL_DATA = {
  general: {
    schoolName: "Government Senior Secondary School 52 LNP (Manjhuwas)",
    schoolNameHi: "राजकीय उच्च माध्यमिक विद्यालय 52 LNP (मांझूवास)",
    motto: "Inspire • Learn • Lead",
    mottoHi: "प्रेरणा • ज्ञान • नेतृत्व",
    udise: "08010205201",
    board: "RBSE (Rajasthan Board of Secondary Education, Ajmer)",
    established: "1968",
    address: "Village 52 LNP (Manjhuwas), Tehsil Padampur, District Sri Ganganagar, Rajasthan - 335041",
    addressHi: "ग्राम 52 एलएनपी (मांझूवास), तहसील पदमपुर, जिला श्रीगंगानगर, राजस्थान - 335041",
    phone: "+91 154 2852052 / +91 94140 XXXXX",
    email: "gsss52lnp.sriganganagar@gmail.com",
    principal: "Smt. Mamta",
    shalaDarpanCode: "217004",
    shalaDarpanUrl: "https://rajshaladarpan.rajasthan.gov.in",
    principalHi: "श्रीमती ममता (प्रधानाचार्य)",
  },

  stats: [
    { num: "950+", labelEn: "Enrolled Students", labelHi: "नामांकित विद्यार्थी" },
    { num: "100%", labelEn: "RBSE Board Pass Rate", labelHi: "बोर्ड परीक्षा परिणाम" },
    { num: "35+", labelEn: "Dedicated Faculty", labelHi: "योग्य शिक्षक एवं स्टाफ" },
    { num: "18+", labelEn: "Smart Labs & Classrooms", labelHi: "स्मार्ट कक्षाएं व प्रयोगशालाएं" }
  ],

  quickAccess: [
    {
      id: "academics",
      icon: "fa-solid fa-graduation-cap",
      titleEn: "Academics",
      titleHi: "शैक्षणिक कार्यक्रम",
      descEn: "RBSE curriculum from Class 1 to 12th in Arts, Science & Agriculture.",
      descHi: "कक्षा 1 से 12वीं तक कला, विज्ञान एवं कृषि संकाय का उत्कृष्ट पाठ्यक्रम।",
      link: "#academics"
    },
    {
      id: "admissions",
      icon: "fa-solid fa-file-signature",
      titleEn: "Admissions",
      titleHi: "प्रवेश 2026-27",
      descEn: "Free admission for girls & boys under RTE & Rajasthan Govt norms.",
      descHi: "आरटीई व राजस्थान सरकार नियमानुसार निःशुल्क एवं सुगम प्रवेश।",
      link: "#admissions"
    },
    {
      id: "student-life",
      icon: "fa-solid fa-trophy",
      titleEn: "Student Life",
      titleHi: "विद्यार्थी जीवन",
      descEn: "NCC, NSS, Scouts & Guides, Sports, Cultural Clubs & Eco Club.",
      descHi: "एनसीसी, एनएसएस, स्काउट-गाइड, खेलकूद और सांस्कृतिक गतिविधियां।",
      link: "#student-life"
    },
    {
      id: "facilities",
      icon: "fa-solid fa-flask-vial",
      titleEn: "Facilities",
      titleHi: "संसाधन व सुविधाएं",
      descEn: "ICT Smart Labs, Science Labs, Library, PM POSHAN Kitchen.",
      descHi: "आईसीटी कंप्यूटर लैब, विज्ञान प्रयोगशालाएं, समृद्ध पुस्तकालय।",
      link: "#facilities"
    },
    {
      id: "notices",
      icon: "fa-solid fa-bullhorn",
      titleEn: "Notice Board",
      titleHi: "सूचना पट्ट",
      descEn: "RBSE board timetables, scholarship updates & circulars.",
      descHi: "आरबीएसई बोर्ड समय सारणी, छात्रवृत्ति एवं विभागीय आदेश।",
      link: "#notices"
    }
  ],

  upcomingEvents: [],

  latestNews: [],

  notices: [],

    academicStreams: [
    {
      id: "science",
      nameEn: "Science Stream (विज्ञान संकाय)",
      nameHi: "विज्ञान संकाय (Science)",
      banner: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=600&q=80",
      badge: "RBSE Certified",
      descEn: "Advanced Physics, Chemistry & Biology with state-of-the-art modern laboratory practicals.",
      descHi: "भौतिकी, रसायन एवं जीव विज्ञान के साथ आधुनिक प्रयोगशाला में प्रायोगिक शिक्षण।",
      subjects: ["Physics (भौतिक विज्ञान)", "Chemistry (रसायन विज्ञान)", "Biology (जीव विज्ञान)"]
    },
    {
      id: "arts",
      nameEn: "Arts & Humanities (कला संकाय)",
      nameHi: "कला संकाय (Arts)",
      banner: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=600&q=80",
      badge: "Popular Choice",
      descEn: "Rich foundation in Political Science, Geography, Sociology, and Literature.",
      descHi: "राजनीति विज्ञान, भूगोल, समाजशास्त्र एवं भाषा साहित्य में उत्कृष्ट शिक्षण।",
      subjects: ["Political Science (राजनीति विज्ञान)", "Geography (भूगोल)", "Sociology (समाजशास्त्र)", "Punjabi / Sanskrit (तृतीय भाषा)"]
    },
    {
      id: "vocational",
      nameEn: "Vocational & Computer Education (कम्प्यूटर शिक्षा)",
      nameHi: "व्यावसायिक एवं कम्प्यूटर शिक्षा",
      banner: "assets/images/campus/ict-computer-lab.jpg",
      badge: "Digital India",
      descEn: "Computer Science, ICT Smart Lab practicals, Digital Literacy & Practical Vocational training under BCI.",
      descHi: "कम्प्यूटर विज्ञान, आईसीटी स्मार्ट लैब, डिजिटल साक्षरता एवं व्यावहारिक कम्प्यूटर प्रशिक्षण।",
      subjects: ["Computer Science (कम्प्यूटर विज्ञान)", "Information Tech (IT)", "Digital Skills", "Financial Literacy"]
    }
  ],

  facilities: [
    {
      titleEn: "ICT Smart Classroom & Computer Lab",
      titleHi: "आईसीटी स्मार्ट क्लासरूम व कंप्यूटर लैब",
      descEn: "Equipped with 30 high-speed PCs, interactive flat interactive panels, high-speed broadband and DIKSHA portal integration.",
      descHi: "30 आधुनिक कंप्यूटर, इंटरैक्टिव डिजिटल बोर्ड, हाई-स्पीड इंटरनेट और दीक्षा पोर्टल से सुसज्जित।",
      image: "assets/images/campus/ict-computer-lab.jpg"
    },
    {
      titleEn: "Integrated Science & Composite Labs",
      titleHi: "एकीकृत विज्ञान एवं प्रायोगिक प्रयोगशाला",
      descEn: "Specialized labs for Physics, Chemistry, Biology and Agriculture experiments with modern apparatus and safety gear.",
      descHi: "भौतिक, रसायन, जीव विज्ञान एवं कृषि परीक्षणों हेतु आधुनिक उपकरणों से सुसज्जित प्रयोगशालाएं।",
      image: "assets/images/campus/main-gate-building.jpg"
    },
    {
      titleEn: "School Library & Reading Room",
      titleHi: "विद्यालय पुस्तकालय एवं वाचनालय",
      descEn: "Over 5,000 reference books, competitive exam guides (REET, NDA, NEET, JET), daily newspapers and periodicals.",
      descHi: "5,000+ संदर्भ पुस्तकें, प्रतियोगी परीक्षा मार्गदर्शिकाएं, दैनिक समाचार पत्र व ज्ञानवर्धक पत्रिकाएं।",
      image: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=600&q=80"
    },
    {
      titleEn: "PM POSHAN Hygienic Kitchen & Dining",
      titleHi: "पीएम पोषण स्वच्छ रसोई व भोजनालय",
      descEn: "Fresh, nutritious, hot cooked meals prepared daily under strict hygiene protocols for primary & middle students.",
      descHi: "प्राथमिक व उच्च प्राथमिक विद्यार्थियों हेतु दैनिक ताजा, पौष्टिक व स्वादिष्ट गरम भोजन की व्यवस्था।",
      image: "assets/images/events/tree-plantation-ecoclub.jpg"
    },
    {
      titleEn: "Sports Complex & Athletic Grounds",
      titleHi: "खेल परिसर एवं एथलेटिक मैदान",
      descEn: "Dedicated tracks and courts for Kabbadi, Kho-Kho, Volleyball, Cricket, Badminton and Track & Field.",
      descHi: "कबड्डी, खो-खो, वॉलीबॉल, क्रिकेट और एथलेटिक्स हेतु विशाल खेल मैदान व खेल सामग्री।",
      image: "assets/images/events/school-sports-team.jpg"
    },
    {
      titleEn: "RO Purified Drinking Water & Solar Power",
      titleHi: "आर.ओ. शीतल पेयजल व सौर ऊर्जा संयंत्र",
      descEn: "Continuous 10kVA solar power backup, clean multi-stage RO drinking water plants and eco-friendly green campus.",
      descHi: "10 केवीए सौर ऊर्जा संयंत्र, बहुस्तरीय आरओ शुद्ध शीतल जल और हरा-भरा पर्यावरण अनुकूल परिसर।",
      image: "https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=600&q=80"
    }
  ],

  schemes: [
    {
      icon: "fa-solid fa-shirt",
      titleEn: "Free Uniform & Stitching Aid",
      titleHi: "निःशुल्क स्कूल यूनिफॉर्म योजना",
      descEn: "Two sets of free school uniforms plus direct bank transfer (DBT) stitching assistance for eligible students.",
      descHi: "पात्र छात्र-छात्राओं को दो सेट निःशुल्क विद्यालय पोशाक एवं सिलाई हेतु डीबीटी राशि।"
    },
    {
      icon: "fa-solid fa-book-open-reader",
      titleEn: "Free Textbooks Scheme",
      titleHi: "निःशुल्क पाठ्यपुस्तक वितरण",
      descEn: "100% free RBSE textbooks provided to all enrolled boys and girls from Class 1 to Class 12.",
      descHi: "कक्षा 1 से 12वीं तक अध्ययनरत समस्त विद्यार्थियों को 100% निःशुल्क पाठ्यपुस्तकें।"
    },
    {
      icon: "fa-solid fa-award",
      titleEn: "Gargi & Balika Protsahan Puraskar",
      titleHi: "गार्गी व बालिका प्रोत्साहन पुरस्कार",
      descEn: "Merit award and financial incentive to meritorious girl students securing 75%+ marks in 10th & 12th board exams.",
      descHi: "बोर्ड परीक्षाओं में 75% से अधिक अंक प्राप्त करने वाली मेधावी छात्राओं को प्रमाण पत्र व प्रोत्साहन राशि।"
    },
    {
      icon: "fa-solid fa-laptop",
      titleEn: "Free Smart Tablet / Laptop Scheme",
      titleHi: "मेधावी छात्र लैपटॉप / टैबलेट योजना",
      descEn: "State government distribution of smart learning devices to top academic rankers in 8th, 10th, and 12th.",
      descHi: "कक्षा 8वीं, 10वीं व 12वीं के मेरिट प्राप्त विद्यार्थियों को नि:शुल्क डिजिटल डिवाइस।"
    },
    {
      icon: "fa-solid fa-bowl-rice",
      titleEn: "PM POSHAN / Mid-Day Meal",
      titleHi: "पीएम पोषण / मिड-डे मील योजना",
      descEn: "Daily balanced nutritional hot meal along with fortified milk (Bal Gopal Yojana) for healthy student growth.",
      descHi: "दैनिक पौष्टिक गरम भोजन एवं बाल गोपाल योजना के अंतर्गत सप्ताह में निर्धारित दिवसों पर गर्म दूध।"
    },
    {
      icon: "fa-solid fa-bicycle",
      titleEn: "Free Bicycle & Transport Voucher",
      titleHi: "निःशुल्क साइकिल / ट्रांसपोर्ट वाउचर",
      descEn: "Free bicycles to rural girl students entering Class 9th and transport reimbursement for distant habitations.",
      descHi: "कक्षा 9 में प्रवेशित बालिकाओं को निःशुल्क साइकिल एवं दूरस्थ ढाणियों से आने वाले छात्रों को वाउचर।"
    }
  ],

      faculty: [
    {
      name: "Smt. Mamta",
      nameHi: "श्रीमती ममता",
      designationEn: "Principal & Equivalent",
      designationHi: "प्रधानाचार्य (Principal)",
      subjectEn: "School Administration & Leadership",
      subjectHi: "संस्था प्रधान एवं प्रशासन",
      photo: "assets/images/faculty/mamta-principal.jpg"
    },
    {
      name: "Smt. Surbha",
      nameHi: "श्रीमती सुरभा",
      designationEn: "Vice Principal",
      designationHi: "उप-प्रधानाचार्य (Vice Principal)",
      subjectEn: "School Management & Academics",
      subjectHi: "शैक्षणिक एवं प्रशासनिक समन्वय",
      photo: "assets/images/faculty/surbha-vp.jpg"
    },
    {
      name: "Smt. Renu Choudhary",
      nameHi: "श्रीमती रेनू चौधरी",
      designationEn: "Lecturer (I Gr.)",
      designationHi: "व्याख्याता (प्रथम श्रेणी)",
      subjectEn: "Political Science",
      subjectHi: "राजनीति विज्ञान",
      photo: "assets/images/faculty/renu-choudhary.jpg"
    },
    {
      name: "Sh. Surya Kant",
      nameHi: "श्री सूर्य कांत",
      designationEn: "Lecturer (I Gr.)",
      designationHi: "व्याख्याता (प्रथम श्रेणी)",
      subjectEn: "Geography",
      subjectHi: "भूगोल",
      photo: "assets/images/faculty/surya-kant.jpg"
    },
    {
      name: "Sh. Sanjay Takhar",
      nameHi: "श्री संजय तखर",
      designationEn: "Computer Teacher (BCI)",
      designationHi: "कम्प्यूटर शिक्षक (बेसिक कम्प्यूटर अनुदेशक)",
      subjectEn: "Computer Science & ICT Smart Lab",
      subjectHi: "कम्प्यूटर विज्ञान एवं आईसीटी लैब प्रभारी",
      photo: "assets/images/faculty/sanjay-takhar.jpg"
    },
    {
      name: "Sh. Rajveer",
      nameHi: "श्री राजवीर",
      designationEn: "Physical Education Teacher (PET III Gr.)",
      designationHi: "शारीरिक शिक्षक (पीईटी तृतीय श्रेणी)",
      subjectEn: "Sports, Athletics & Yoga",
      subjectHi: "खेलकूद, एथलेटिक्स एवं योग",
      photo: "assets/images/faculty/rajveer-pet.jpg"
    },
    {
      name: "Smt. Anju Bala",
      nameHi: "श्रीमती अंजू बाला",
      designationEn: "Senior Teacher (II Gr.)",
      designationHi: "वरिष्ठ अध्यापक (द्वितीय श्रेणी)",
      subjectEn: "Hindi Literature & Grammar",
      subjectHi: "हिन्दी साहित्य एवं व्याकरण",
      photo: "assets/images/faculty/anju-bala.jpg"
    },
    {
      name: "Sh. Ashok Kumar",
      nameHi: "श्री अशोक कुमार",
      designationEn: "Senior Teacher (II Gr.)",
      designationHi: "वरिष्ठ अध्यापक (द्वितीय श्रेणी)",
      subjectEn: "English Language & Lit.",
      subjectHi: "अंग्रेजी भाषा व साहित्य",
      photo: "assets/images/faculty/ashok-kumar.jpg"
    },
    {
      name: "Smt. Manju Bala",
      nameHi: "श्रीमती मंजू बाला",
      designationEn: "Senior Teacher (II Gr.)",
      designationHi: "वरिष्ठ अध्यापक (द्वितीय श्रेणी)",
      subjectEn: "General Science",
      subjectHi: "सामान्य विज्ञान एवं लैब",
      photo: "assets/images/faculty/manju-bala.jpg"
    },
    {
      name: "Sh. Manohar Lal Sihag",
      nameHi: "श्री मनोहर लाल सिहाग",
      designationEn: "Senior Teacher (II Gr.)",
      designationHi: "वरिष्ठ अध्यापक (द्वितीय श्रेणी)",
      subjectEn: "Mathematics",
      subjectHi: "गणित शिक्षण",
      photo: "assets/images/faculty/manohar-lal.jpg"
    },
    {
      name: "Smt. Parminder Kaur",
      nameHi: "श्रीमती परमिंदर कौर",
      designationEn: "Senior Teacher (II Gr.)",
      designationHi: "वरिष्ठ अध्यापक (द्वितीय श्रेणी)",
      subjectEn: "Punjabi (Third Language)",
      subjectHi: "पंजाबी (तृतीय भाषा)",
      photo: "assets/images/faculty/parminder-kaur.jpg"
    },
    {
      name: "Smt. Chand Rani",
      nameHi: "श्रीमती चांद रानी",
      designationEn: "Teacher (III Gr.) Level 2",
      designationHi: "अध्यापक (तृतीय श्रेणी) लेवल-2",
      subjectEn: "Hindi",
      subjectHi: "हिन्दी शिक्षण",
      photo: "assets/images/faculty/chand-rani.jpg"
    },
    {
      name: "Sh. Kamlesh Khichar",
      nameHi: "श्री कमलेश खीचड़",
      designationEn: "Teacher",
      designationHi: "अध्यापक",
      subjectEn: "English",
      subjectHi: "अंग्रेजी शिक्षण",
      photo: "assets/images/faculty/kamlesh-khichar.jpg"
    },
    {
      name: "Smt. Lalita Rani",
      nameHi: "श्रीमती ललिता रानी",
      designationEn: "Teacher (III Gr.) Level 2",
      designationHi: "अध्यापक (तृतीय श्रेणी) लेवल-2",
      subjectEn: "Hindi",
      subjectHi: "हिन्दी शिक्षण",
      photo: "assets/images/faculty/test.jpg"
    },
    {
      name: "Smt. Savita",
      nameHi: "श्रीमती सविता",
      designationEn: "Teacher (III Gr.) Level 2",
      designationHi: "अध्यापक (तृतीय श्रेणी) लेवल-2",
      subjectEn: "English",
      subjectHi: "अंग्रेजी शिक्षण",
      photo: "assets/images/faculty/test.jpg"
    },
    {
      name: "Smt. Veena Sharma",
      nameHi: "श्रीमती वीणा शर्मा",
      designationEn: "Teacher (III Gr.) Level 2",
      designationHi: "अध्यापक (तृतीय श्रेणी) लेवल-2",
      subjectEn: "Mathematics / Science",
      subjectHi: "गणित एवं विज्ञान",
      photo: "assets/images/faculty/test.jpg"
    },
    {
      name: "Sh. Suresh Kumar",
      nameHi: "श्री सुरेश कुमार",
      designationEn: "Teacher",
      designationHi: "अध्यापक",
      subjectEn: "Social Studies (SST)",
      subjectHi: "सामाजिक अध्ययन",
      photo: "assets/images/faculty/test.jpg"
    },
    {
      name: "Sh. Ajab Maliya",
      nameHi: "श्री अजब मालिया",
      designationEn: "Teacher (III Gr.) Level 1",
      designationHi: "अध्यापक (तृतीय श्रेणी) लेवल-1",
      subjectEn: "Primary Education",
      subjectHi: "प्राथमिक शिक्षा प्रभाग",
      photo: "assets/images/faculty/ajab-maliya.jpg"
    },
    {
      name: "Sh. Balram Chandel",
      nameHi: "श्री बलराम चंदेल",
      designationEn: "Teacher (III Gr.) Level 1",
      designationHi: "अध्यापक (तृतीय श्रेणी) लेवल-1",
      subjectEn: "Primary Education",
      subjectHi: "प्राथमिक शिक्षा प्रभाग",
      photo: "assets/images/faculty/balram-chandel.jpg"
    },
    {
      name: "Smt. Urmila",
      nameHi: "श्रीमती उर्मिला",
      designationEn: "Teacher (III Gr.) Level 1",
      designationHi: "अध्यापक (तृतीय श्रेणी) लेवल-1",
      subjectEn: "Primary Education",
      subjectHi: "प्राथमिक शिक्षा प्रभाग",
      photo: "assets/images/faculty/test.jpg"
    },
    {
      name: "Sh. Balram Verma",
      nameHi: "श्री बलराम वर्मा",
      designationEn: "Administrative Staff",
      designationHi: "मंत्रालयिक कर्मचारी",
      subjectEn: "School Office & Administration",
      subjectHi: "कार्यालय प्रशासन",
      photo: "assets/images/faculty/balram-verma.jpg"
    },
    {
      name: "Smt. Poonam",
      nameHi: "श्रीमती पूनम",
      designationEn: "Junior Assistant",
      designationHi: "कनिष्ठ सहायक (Junior Assistant)",
      subjectEn: "Office & Accounts",
      subjectHi: "कार्यालय एवं लेखा प्रबंधन",
      photo: "assets/images/faculty/test.jpg"
    },
    {
      name: "Smt. Urmila",
      nameHi: "श्रीमती उर्मिला",
      designationEn: "Class IV Staff",
      designationHi: "चतुर्थ श्रेणी कर्मचारी",
      subjectEn: "Campus Support Services",
      subjectHi: "सहायक कर्मचारी",
      photo: "assets/images/faculty/test.jpg"
    }
  ],

  testimonials: [],


  boardResults10th2026: {
    "year": "2026",
    "class": "10th",
    "schoolCode": "1240860 / 217004",
    "schoolName": "Govt. Sr. Sec. School 52 LNP (Manjhuwas), Padampur, Sri Ganganagar",
    "summary": {
        "totalCandidates": 53,
        "totalPassed": 53,
        "passRate": "100%",
        "firstDivision": 39,
        "secondDivision": 12,
        "thirdDivision": 2
    },
    "toppers": [
        {
            "rank": 1,
            "roll": "1851711",
            "name": "Vaibhav Godara",
            "father": "Surendra Kumar",
            "stream": "Class 10th",
            "marks": 584,
            "maxMarks": 600,
            "percent": "97.33%",
            "badge": "School Overall Topper (97.33%)"
        },
        {
            "rank": 2,
            "roll": "1851704",
            "name": "Saneha",
            "father": "Vinod Kumar",
            "stream": "Class 10th",
            "marks": 568,
            "maxMarks": 600,
            "percent": "94.67%",
            "badge": "2nd Rank (Gargi Puraskar)"
        },
        {
            "rank": 3,
            "roll": "1851675",
            "name": "Dilasa",
            "father": "Ram Swaroop",
            "stream": "Class 10th",
            "marks": 552,
            "maxMarks": 600,
            "percent": "92.00%",
            "badge": "3rd Rank (Gargi Puraskar)"
        },
        {
            "rank": 4,
            "roll": "1851712",
            "name": "Vikrant",
            "father": "Prakash Chander",
            "stream": "Class 10th",
            "marks": 543,
            "maxMarks": 600,
            "percent": "90.50%",
            "badge": "4th Rank (State Merit)"
        },
        {
            "rank": 5,
            "roll": "1851709",
            "name": "Tamanna",
            "father": "Sandeep Kumar",
            "stream": "Class 10th",
            "marks": 542,
            "maxMarks": 600,
            "percent": "90.33%",
            "badge": "5th Rank (Gargi Puraskar)"
        },
        {
            "rank": 6,
            "roll": "1851679",
            "name": "Divya",
            "father": "Omparkash",
            "stream": "Class 10th",
            "marks": 541,
            "maxMarks": 600,
            "percent": "90.17%",
            "badge": "6th Rank (Gargi Puraskar)"
        }
    ],
    "students": [
        {
            "sNo": 1,
            "roll": "1851663",
            "name": "Aaina",
            "gender": "F",
            "father": "Santosh Kumar",
            "hindi": 57,
            "english": "87D",
            "science": 59,
            "socSci": 43,
            "maths": 43,
            "thirdLang": "Punjabi: 72",
            "total": 361,
            "percent": 60.17,
            "result": "First Division"
        },
        {
            "sNo": 2,
            "roll": "1851664",
            "name": "Akshay Kumar",
            "gender": "M",
            "father": "Puran Ram Jyani",
            "hindi": 59,
            "english": "85D",
            "science": 58,
            "socSci": 59,
            "maths": 54,
            "thirdLang": "Punjabi: 64",
            "total": 379,
            "percent": 63.17,
            "result": "First Division"
        },
        {
            "sNo": 3,
            "roll": "1851665",
            "name": "Akshra",
            "gender": "F",
            "father": "Mohan Lal",
            "hindi": 69,
            "english": "85D",
            "science": 63,
            "socSci": 56,
            "maths": 43,
            "thirdLang": "Punjabi: 81D",
            "total": 397,
            "percent": 66.17,
            "result": "First Division"
        },
        {
            "sNo": 4,
            "roll": "1851666",
            "name": "Ambika",
            "gender": "F",
            "father": "Tekchand",
            "hindi": 69,
            "english": "91D",
            "science": 69,
            "socSci": 60,
            "maths": 61,
            "thirdLang": "Punjabi: 85D",
            "total": 435,
            "percent": 72.5,
            "result": "First Division"
        },
        {
            "sNo": 5,
            "roll": "1851667",
            "name": "Anita",
            "gender": "F",
            "father": "Banwari Lal",
            "hindi": 73,
            "english": "80D",
            "science": 54,
            "socSci": 52,
            "maths": 48,
            "thirdLang": "Punjabi: 68",
            "total": 375,
            "percent": 62.5,
            "result": "First Division"
        },
        {
            "sNo": 6,
            "roll": "1851668",
            "name": "Anjali",
            "gender": "F",
            "father": "Ram Kumar",
            "hindi": 74,
            "english": "82D",
            "science": 54,
            "socSci": 61,
            "maths": 57,
            "thirdLang": "Punjabi: 75D",
            "total": 403,
            "percent": 67.17,
            "result": "First Division"
        },
        {
            "sNo": 7,
            "roll": "1851669",
            "name": "Anjali",
            "gender": "F",
            "father": "Banwari Lal",
            "hindi": 51,
            "english": 60,
            "science": 48,
            "socSci": 38,
            "maths": 44,
            "thirdLang": "Punjabi: 56",
            "total": 297,
            "percent": 49.5,
            "result": "Second Division"
        },
        {
            "sNo": 8,
            "roll": "1851670",
            "name": "Bharat",
            "gender": "M",
            "father": "Amara Ram",
            "hindi": 56,
            "english": 71,
            "science": 63,
            "socSci": 57,
            "maths": 57,
            "thirdLang": "Punjabi: 74",
            "total": 378,
            "percent": 63.0,
            "result": "First Division"
        },
        {
            "sNo": 9,
            "roll": "1851671",
            "name": "Bhumika",
            "gender": "F",
            "father": "Banwari Lal",
            "hindi": 58,
            "english": 51,
            "science": 53,
            "socSci": 51,
            "maths": 33,
            "thirdLang": "Punjabi: 70",
            "total": 316,
            "percent": 52.67,
            "result": "Second Division"
        },
        {
            "sNo": 10,
            "roll": "1851672",
            "name": "Deepak",
            "gender": "M",
            "father": "Dulichand",
            "hindi": 44,
            "english": "31G",
            "science": 50,
            "socSci": "32G",
            "maths": 45,
            "thirdLang": "Punjabi: 51",
            "total": 253,
            "percent": 42.17,
            "result": "Third Division (By Grace)"
        },
        {
            "sNo": 11,
            "roll": "1851673",
            "name": "Diksha",
            "gender": "F",
            "father": "Deendayal",
            "hindi": 73,
            "english": "88D",
            "science": 57,
            "socSci": 61,
            "maths": 62,
            "thirdLang": "Punjabi: 82D",
            "total": 423,
            "percent": 70.5,
            "result": "First Division"
        },
        {
            "sNo": 12,
            "roll": "1851674",
            "name": "Diksha Sharma",
            "gender": "F",
            "father": "Hanuman Prasad",
            "hindi": 70,
            "english": "95D",
            "science": 68,
            "socSci": 60,
            "maths": 66,
            "thirdLang": "Punjabi: 78D",
            "total": 437,
            "percent": 72.83,
            "result": "First Division"
        },
        {
            "sNo": 13,
            "roll": "1851675",
            "name": "Dilasa",
            "gender": "F",
            "father": "Ram Swaroop",
            "hindi": "93D",
            "english": "98D",
            "science": "84D",
            "socSci": "90D",
            "maths": "89D",
            "thirdLang": "Punjabi: 98D",
            "total": 552,
            "percent": 92.0,
            "result": "First Division"
        },
        {
            "sNo": 14,
            "roll": "1851676",
            "name": "Dilkhush",
            "gender": "M",
            "father": "Rampratap",
            "hindi": "76D",
            "english": "98D",
            "science": 74,
            "socSci": 61,
            "maths": 60,
            "thirdLang": "Punjabi: 91D",
            "total": 460,
            "percent": 76.67,
            "result": "First Division"
        },
        {
            "sNo": 15,
            "roll": "1851677",
            "name": "Dimple",
            "gender": "F",
            "father": "Sanjay Dutt",
            "hindi": 73,
            "english": "91D",
            "science": 61,
            "socSci": 62,
            "maths": 67,
            "thirdLang": "Punjabi: 89D",
            "total": 443,
            "percent": 73.83,
            "result": "First Division"
        },
        {
            "sNo": 16,
            "roll": "1851678",
            "name": "Divya",
            "gender": "F",
            "father": "Raja Ram",
            "hindi": "85D",
            "english": "94D",
            "science": "84D",
            "socSci": "84D",
            "maths": "92D",
            "thirdLang": "Punjabi: 96D",
            "total": 535,
            "percent": 89.17,
            "result": "First Division"
        },
        {
            "sNo": 17,
            "roll": "1851679",
            "name": "Divya",
            "gender": "F",
            "father": "Omparkash",
            "hindi": "87D",
            "english": "99D",
            "science": "83D",
            "socSci": "91D",
            "maths": "83D",
            "thirdLang": "Punjabi: 98D",
            "total": 541,
            "percent": 90.17,
            "result": "First Division"
        },
        {
            "sNo": 18,
            "roll": "1851680",
            "name": "Gagandeep",
            "gender": "M",
            "father": "Nanu Ram",
            "hindi": 68,
            "english": "83D",
            "science": 59,
            "socSci": 56,
            "maths": 60,
            "thirdLang": "Punjabi: 86D",
            "total": 412,
            "percent": 68.67,
            "result": "First Division"
        },
        {
            "sNo": 19,
            "roll": "1851681",
            "name": "Geeta",
            "gender": "F",
            "father": "Dalu Ram",
            "hindi": 68,
            "english": 55,
            "science": 51,
            "socSci": 44,
            "maths": 44,
            "thirdLang": "Punjabi: 66",
            "total": 328,
            "percent": 54.67,
            "result": "Second Division"
        },
        {
            "sNo": 20,
            "roll": "1851682",
            "name": "Kamaljeet",
            "gender": "M",
            "father": "Banshi Lal",
            "hindi": 59,
            "english": 73,
            "science": 56,
            "socSci": 61,
            "maths": 49,
            "thirdLang": "Punjabi: 74",
            "total": 372,
            "percent": 62.0,
            "result": "First Division"
        },
        {
            "sNo": 21,
            "roll": "1851683",
            "name": "Kavita",
            "gender": "F",
            "father": "Ram Pratap",
            "hindi": "84D",
            "english": "99D",
            "science": 72,
            "socSci": 68,
            "maths": "81D",
            "thirdLang": "Punjabi: 97D",
            "total": 501,
            "percent": 83.5,
            "result": "First Division"
        },
        {
            "sNo": 22,
            "roll": "1851684",
            "name": "Khushbu",
            "gender": "F",
            "father": "Nanu Ram",
            "hindi": 59,
            "english": "93D",
            "science": 55,
            "socSci": 48,
            "maths": 55,
            "thirdLang": "Punjabi: 85D",
            "total": 395,
            "percent": 65.83,
            "result": "First Division"
        },
        {
            "sNo": 23,
            "roll": "1851685",
            "name": "Komal",
            "gender": "F",
            "father": "Shrvan Kumar",
            "hindi": 54,
            "english": "78D",
            "science": 57,
            "socSci": 40,
            "maths": 45,
            "thirdLang": "Punjabi: 83D",
            "total": 357,
            "percent": 59.5,
            "result": "Second Division"
        },
        {
            "sNo": 24,
            "roll": "1851686",
            "name": "Komal Choudhary",
            "gender": "F",
            "father": "Bheemsen",
            "hindi": 65,
            "english": "85D",
            "science": 63,
            "socSci": 57,
            "maths": 58,
            "thirdLang": "Punjabi: 66",
            "total": 394,
            "percent": 65.67,
            "result": "First Division"
        },
        {
            "sNo": 25,
            "roll": "1851687",
            "name": "Kuldeep",
            "gender": "M",
            "father": "Jagdish",
            "hindi": 49,
            "english": 48,
            "science": 50,
            "socSci": "31G",
            "maths": 46,
            "thirdLang": "Punjabi: 52",
            "total": 276,
            "percent": 46.0,
            "result": "Second Division (By Grace)"
        },
        {
            "sNo": 26,
            "roll": "1851688",
            "name": "Kumkum",
            "gender": "F",
            "father": "Shankar Lal",
            "hindi": 48,
            "english": 73,
            "science": 49,
            "socSci": 44,
            "maths": 43,
            "thirdLang": "Punjabi: 60",
            "total": 317,
            "percent": 52.83,
            "result": "Second Division"
        },
        {
            "sNo": 27,
            "roll": "1851689",
            "name": "Mamta",
            "gender": "F",
            "father": "Laxman",
            "hindi": 62,
            "english": "78D",
            "science": 55,
            "socSci": 47,
            "maths": 48,
            "thirdLang": "Punjabi: 68",
            "total": 358,
            "percent": 59.67,
            "result": "Second Division"
        },
        {
            "sNo": 28,
            "roll": "1851690",
            "name": "Mohit",
            "gender": "M",
            "father": "Dara Ram",
            "hindi": 56,
            "english": "78D",
            "science": 55,
            "socSci": 50,
            "maths": 57,
            "thirdLang": "Punjabi: 64",
            "total": 360,
            "percent": 60.0,
            "result": "First Division"
        },
        {
            "sNo": 29,
            "roll": "1851691",
            "name": "Monika",
            "gender": "F",
            "father": "Shyoprakash",
            "hindi": 70,
            "english": "89D",
            "science": 66,
            "socSci": 68,
            "maths": 63,
            "thirdLang": "Punjabi: 86D",
            "total": 442,
            "percent": 73.67,
            "result": "First Division"
        },
        {
            "sNo": 30,
            "roll": "1851692",
            "name": "Monu",
            "gender": "M",
            "father": "Daulat Ram",
            "hindi": 67,
            "english": "89D",
            "science": 59,
            "socSci": 57,
            "maths": 69,
            "thirdLang": "Punjabi: 87D",
            "total": 428,
            "percent": 71.33,
            "result": "First Division"
        },
        {
            "sNo": 31,
            "roll": "1851693",
            "name": "Nalin Yadav",
            "gender": "M",
            "father": "Pawan Kumar",
            "hindi": "96D",
            "english": "87D",
            "science": "88D",
            "socSci": "83D",
            "maths": 73,
            "thirdLang": "Sanskrit: 82D",
            "total": 509,
            "percent": 84.83,
            "result": "First Division"
        },
        {
            "sNo": 32,
            "roll": "1851694",
            "name": "Navneet Verma",
            "gender": "M",
            "father": "Rakesh Kumar",
            "hindi": 69,
            "english": "92D",
            "science": 72,
            "socSci": 61,
            "maths": "75D",
            "thirdLang": "Punjabi: 73",
            "total": 442,
            "percent": 73.67,
            "result": "First Division"
        },
        {
            "sNo": 33,
            "roll": "1851695",
            "name": "Neha",
            "gender": "F",
            "father": "Paale Khan",
            "hindi": 59,
            "english": "77D",
            "science": 58,
            "socSci": 48,
            "maths": 44,
            "thirdLang": "Punjabi: 74",
            "total": 360,
            "percent": 60.0,
            "result": "First Division"
        },
        {
            "sNo": 34,
            "roll": "1851696",
            "name": "Neha Suthar",
            "gender": "F",
            "father": "Bajrang",
            "hindi": 70,
            "english": "91D",
            "science": 61,
            "socSci": 60,
            "maths": 56,
            "thirdLang": "Punjabi: 75D",
            "total": 413,
            "percent": 68.83,
            "result": "First Division"
        },
        {
            "sNo": 35,
            "roll": "1851697",
            "name": "Pawan",
            "gender": "M",
            "father": "Sajan Ram",
            "hindi": 57,
            "english": 69,
            "science": 51,
            "socSci": 51,
            "maths": 57,
            "thirdLang": "Punjabi: 57",
            "total": 342,
            "percent": 57.0,
            "result": "Second Division"
        },
        {
            "sNo": 36,
            "roll": "1851698",
            "name": "Poonam",
            "gender": "F",
            "father": "Harji Ram",
            "hindi": "84D",
            "english": "91D",
            "science": 61,
            "socSci": 69,
            "maths": 64,
            "thirdLang": "Punjabi: 91D",
            "total": 460,
            "percent": 76.67,
            "result": "First Division"
        },
        {
            "sNo": 37,
            "roll": "1851699",
            "name": "Poonam",
            "gender": "F",
            "father": "Himmta Ram",
            "hindi": 62,
            "english": 69,
            "science": 57,
            "socSci": 52,
            "maths": 54,
            "thirdLang": "Punjabi: 60",
            "total": 354,
            "percent": 59.0,
            "result": "Second Division"
        },
        {
            "sNo": 38,
            "roll": "1851700",
            "name": "Priyanka",
            "gender": "F",
            "father": "Hansraj",
            "hindi": 44,
            "english": 46,
            "science": 50,
            "socSci": 43,
            "maths": 40,
            "thirdLang": "Punjabi: 44",
            "total": 267,
            "percent": 44.5,
            "result": "Third Division"
        },
        {
            "sNo": 39,
            "roll": "1851701",
            "name": "Priyanka",
            "gender": "F",
            "father": "Harji Ram",
            "hindi": 61,
            "english": "80D",
            "science": 55,
            "socSci": 47,
            "maths": 45,
            "thirdLang": "Punjabi: 79D",
            "total": 367,
            "percent": 61.17,
            "result": "First Division"
        },
        {
            "sNo": 40,
            "roll": "1851702",
            "name": "Rekha",
            "gender": "F",
            "father": "Gopi Ram",
            "hindi": 43,
            "english": 62,
            "science": 48,
            "socSci": 38,
            "maths": 35,
            "thirdLang": "Punjabi: 47",
            "total": 273,
            "percent": 45.5,
            "result": "Second Division"
        },
        {
            "sNo": 41,
            "roll": "1851703",
            "name": "Sahil",
            "gender": "M",
            "father": "Vinod Kumar",
            "hindi": 61,
            "english": "83D",
            "science": 64,
            "socSci": 54,
            "maths": "81D",
            "thirdLang": "Punjabi: 70",
            "total": 413,
            "percent": 68.83,
            "result": "First Division"
        },
        {
            "sNo": 42,
            "roll": "1851704",
            "name": "Saneha",
            "gender": "F",
            "father": "Vinod Kumar",
            "hindi": "88D",
            "english": "97D",
            "science": "96D",
            "socSci": "95D",
            "maths": "93D",
            "thirdLang": "Punjabi: 99D",
            "total": 568,
            "percent": 94.67,
            "result": "First Division"
        },
        {
            "sNo": 43,
            "roll": "1851705",
            "name": "Sania",
            "gender": "F",
            "father": "Mahaveer",
            "hindi": "76D",
            "english": "89D",
            "science": 67,
            "socSci": 72,
            "maths": 62,
            "thirdLang": "Punjabi: 85D",
            "total": 451,
            "percent": 75.17,
            "result": "First Division"
        },
        {
            "sNo": 44,
            "roll": "1851706",
            "name": "Sanjay Choudhary",
            "gender": "M",
            "father": "Bhimsen",
            "hindi": 66,
            "english": 72,
            "science": 58,
            "socSci": 61,
            "maths": 55,
            "thirdLang": "Punjabi: 74",
            "total": 386,
            "percent": 64.33,
            "result": "First Division"
        },
        {
            "sNo": 45,
            "roll": "1851707",
            "name": "Sumit",
            "gender": "M",
            "father": "Ramesh Kumar",
            "hindi": 59,
            "english": 64,
            "science": 43,
            "socSci": 50,
            "maths": 43,
            "thirdLang": "Punjabi: 66",
            "total": 325,
            "percent": 54.17,
            "result": "Second Division"
        },
        {
            "sNo": 46,
            "roll": "1851708",
            "name": "Surya Prakash",
            "gender": "M",
            "father": "Hari Krishan",
            "hindi": "78D",
            "english": "95D",
            "science": "79D",
            "socSci": "83D",
            "maths": "76D",
            "thirdLang": "Punjabi: 97D",
            "total": 508,
            "percent": 84.67,
            "result": "First Division"
        },
        {
            "sNo": 47,
            "roll": "1851709",
            "name": "Tamanna",
            "gender": "F",
            "father": "Sandeep Kumar",
            "hindi": "90D",
            "english": "99D",
            "science": "85D",
            "socSci": "91D",
            "maths": "77D",
            "thirdLang": "Sanskrit: 100D",
            "total": 542,
            "percent": 90.33,
            "result": "First Division"
        },
        {
            "sNo": 48,
            "roll": "1851710",
            "name": "Teena",
            "gender": "F",
            "father": "Fakir Chand",
            "hindi": 50,
            "english": "84D",
            "science": 52,
            "socSci": 44,
            "maths": 47,
            "thirdLang": "Punjabi: 65",
            "total": 342,
            "percent": 57.0,
            "result": "Second Division"
        },
        {
            "sNo": 49,
            "roll": "1851711",
            "name": "Vaibhav Godara",
            "gender": "M",
            "father": "Surendra Kumar",
            "hindi": "95D",
            "english": "100D",
            "science": "98D",
            "socSci": "96D",
            "maths": "100D",
            "thirdLang": "Punjabi: 95D",
            "total": 584,
            "percent": 97.33,
            "result": "First Division"
        },
        {
            "sNo": 50,
            "roll": "1851712",
            "name": "Vikrant",
            "gender": "M",
            "father": "Prakash Chander",
            "hindi": "90D",
            "english": "98D",
            "science": "83D",
            "socSci": "84D",
            "maths": "92D",
            "thirdLang": "Punjabi: 96D",
            "total": 543,
            "percent": 90.5,
            "result": "First Division"
        },
        {
            "sNo": 51,
            "roll": "1851713",
            "name": "Vishal",
            "gender": "M",
            "father": "Jagdish Kumar",
            "hindi": "79D",
            "english": "98D",
            "science": 64,
            "socSci": 69,
            "maths": 69,
            "thirdLang": "Punjabi: 91D",
            "total": 470,
            "percent": 78.33,
            "result": "First Division"
        },
        {
            "sNo": 52,
            "roll": "1851714",
            "name": "Yachna",
            "gender": "F",
            "father": "Mahender",
            "hindi": "76D",
            "english": "96D",
            "science": 74,
            "socSci": 70,
            "maths": 58,
            "thirdLang": "Punjabi: 91D",
            "total": 465,
            "percent": 77.5,
            "result": "First Division"
        },
        {
            "sNo": 53,
            "roll": "1851715",
            "name": "Yogesh Choudhary",
            "gender": "M",
            "father": "Inder Sain",
            "hindi": 72,
            "english": "93D",
            "science": 65,
            "socSci": 71,
            "maths": "83D",
            "thirdLang": "Punjabi: 68",
            "total": 452,
            "percent": 75.33,
            "result": "First Division"
        }
    ]
},

  boardResults2026: {
    year: '2026',
    schoolCode: '1240860 / 217004',
    schoolName: 'Govt. Sr. Sec. School 52 LNP (Manjhuwas), Padampur, Sri Ganganagar',
    summary: {
      totalCandidates: 32,
      totalPassed: 32,
      passRate: '100%',
      firstDivision: 30,
      secondDivision: 2,
      thirdDivision: 0
    },
    toppers: [
      { rank: 1, roll: '3359329', name: 'Manisha', father: 'Surender Kumar', stream: 'Arts', marks: 466, maxMarks: 500, percent: '93.20%', badge: 'School Topper (Arts)' },
      { rank: 2, roll: '3359328', name: 'Lalita', father: 'Madanlal', stream: 'Arts', marks: 431, maxMarks: 500, percent: '86.20%', badge: '2nd Rank (Arts)' },
      { rank: 3, roll: '2737271', name: 'Karyanika Yadav', father: 'Pawan Kumar', stream: 'Science', marks: 427, maxMarks: 500, percent: '85.40%', badge: 'Science Topper' },
      { rank: 4, roll: '3359324', name: 'Divya', father: 'Rajender', stream: 'Arts', marks: 395, maxMarks: 500, percent: '79.00%', badge: '3rd Rank (Arts)' },
      { rank: 5, roll: '2737275', name: 'Monika', father: 'Surja Ram', stream: 'Science', marks: 366, maxMarks: 500, percent: '73.20%', badge: '2nd Rank (Science)' },
      { rank: 6, roll: '2737274', name: 'Monika', father: 'Sanjay Dutt', stream: 'Science', marks: 347, maxMarks: 500, percent: '69.40%', badge: '3rd Rank (Science)' }
    ],
        scienceStudents: [
      { sNo: 1, roll: '2737270', name: 'Dimple', gender: 'F', father: 'Harji Ram', hindi: 85, english: 48, physics: 53, chemistry: 64, biology: '76D', total: 326, percent: 65.2, result: 'First Division' },
      { sNo: 2, roll: '2737271', name: 'Karyanika Yadav', gender: 'F', father: 'Pawan Kumar', hindi: 97, english: 82, physics: 70, chemistry: '86D', biology: '92D', total: 427, percent: 85.4, result: 'First Division' },
      { sNo: 3, roll: '2737272', name: 'Keshav', gender: 'M', father: 'Mahaveer', hindi: 86, english: 58, physics: 54, chemistry: 60, biology: 73, total: 331, percent: 66.2, result: 'First Division' },
      { sNo: 4, roll: '2737273', name: 'Manish', gender: 'M', father: 'Om Prakash', hindi: 68, english: 67, physics: 52, chemistry: 61, biology: 59, total: 307, percent: 61.4, result: 'First Division' },
      { sNo: 5, roll: '2737274', name: 'Monika', gender: 'F', father: 'Sanjay Dutt', hindi: 74, english: 69, physics: 59, chemistry: 73, biology: 72, total: 347, percent: 69.4, result: 'First Division' },
      { sNo: 6, roll: '2737275', name: 'Monika', gender: 'F', father: 'Surja Ram', hindi: 85, english: 66, physics: 65, chemistry: '77D', biology: 73, total: 366, percent: 73.2, result: 'First Division' },
      { sNo: 7, roll: '2737276', name: 'Nitisha', gender: 'F', father: 'Satpal', hindi: 79, english: 62, physics: 54, chemistry: 67, biology: 63, total: 325, percent: 65.0, result: 'First Division' },
      { sNo: 8, roll: '2737277', name: 'Poonam', gender: 'F', father: 'Syoprakash', hindi: 82, english: 68, physics: 60, chemistry: 62, biology: 70, total: 342, percent: 68.4, result: 'First Division' },
      { sNo: 9, roll: '2737278', name: 'Saniya', gender: 'F', father: 'Jaswant', hindi: 65, english: 48, physics: 54, chemistry: 55, biology: 62, total: 284, percent: 56.8, result: 'Second Division' },
      { sNo: 10, roll: '2737279', name: 'Shiv Kumar', gender: 'M', father: 'Rajender Kumar', hindi: 66, english: 58, physics: 52, chemistry: 56, biology: 58, total: 290, percent: 58.0, result: 'Second Division' },
      { sNo: 11, roll: '2737280', name: 'Sonu', gender: 'M', father: 'Doulat Ram', hindi: 69, english: 66, physics: 60, chemistry: 66, biology: 65, total: 326, percent: 65.2, result: 'First Division' },
      { sNo: 12, roll: '2737281', name: 'Yogesh', gender: 'M', father: 'Kashi Ram', hindi: 75, english: 61, physics: 61, chemistry: 64, biology: 62, total: 323, percent: 64.6, result: 'First Division' }
    ],
        artsStudents: [
      { sNo: 1, roll: '3359316', name: 'Aaina', gender: 'F', father: 'Brijlal', hindi: 79, english: 54, polSci: '86D', geography: '79D', sociology: '83D', total: 381, percent: 76.2, result: 'First Division' },
      { sNo: 2, roll: '3359317', name: 'Abhishek Sharma', gender: 'M', father: 'Arjun Lal Sharma', hindi: 68, english: 52, polSci: '81D', geography: '82D', sociology: 67, total: 350, percent: 70.0, result: 'First Division' },
      { sNo: 3, roll: '3359318', name: 'Amit Kumar', gender: 'M', father: 'Patram', hindi: 82, english: 47, polSci: '82D', geography: '85D', sociology: '75D', total: 371, percent: 74.2, result: 'First Division' },
      { sNo: 4, roll: '3359319', name: 'Arpit', gender: 'M', father: 'Subhash', hindi: 64, english: 54, polSci: '89D', geography: '77D', sociology: 69, total: 353, percent: 70.6, result: 'First Division' },
      { sNo: 5, roll: '3359320', name: 'Bheem Sen', gender: 'M', father: 'Ghanshyam', hindi: 68, english: 38, polSci: '86D', geography: 67, sociology: 69, total: 328, percent: 65.6, result: 'First Division' },
      { sNo: 6, roll: '3359321', name: 'Bhumika', gender: 'F', father: 'Ghanshyam', hindi: 70, english: 48, polSci: '87D', geography: 74, sociology: 73, total: 352, percent: 70.4, result: 'First Division' },
      { sNo: 7, roll: '3359322', name: 'Dharmveer', gender: 'M', father: 'Sahbram', hindi: 70, english: 40, polSci: '88D', geography: 66, sociology: 70, total: 334, percent: 66.8, result: 'First Division' },
      { sNo: 8, roll: '3359323', name: 'Divya', gender: 'F', father: 'Dharmender', hindi: 81, english: 52, polSci: '90D', geography: '77D', sociology: '80D', total: 380, percent: 76.0, result: 'First Division' },
      { sNo: 9, roll: '3359324', name: 'Divya', gender: 'F', father: 'Rajender', hindi: 87, english: 60, polSci: '91D', geography: '78D', sociology: '79D', total: 395, percent: 79.0, result: 'First Division' },
      { sNo: 10, roll: '3359325', name: 'Hemant Kumar', gender: 'M', father: 'Ramnarayan', hindi: 83, english: 63, polSci: '88D', geography: '76D', sociology: '79D', total: 389, percent: 77.8, result: 'First Division' },
      { sNo: 11, roll: '3359326', name: 'Kavita Jakhar', gender: 'F', father: 'Balwant Ram', hindi: 63, english: 52, polSci: 69, geography: 64, sociology: 56, total: 304, percent: 60.8, result: 'First Division' },
      { sNo: 12, roll: '3359327', name: 'Lakshay', gender: 'M', father: 'Naresh Kumar', hindi: 75, english: 68, polSci: '89D', geography: '78D', sociology: '77D', total: 387, percent: 77.4, result: 'First Division' },
      { sNo: 13, roll: '3359328', name: 'Lalita', gender: 'F', father: 'Madanlal', hindi: 84, english: 85, polSci: '93D', geography: '90D', sociology: '79D', total: 431, percent: 86.2, result: 'First Division' },
      { sNo: 14, roll: '3359329', name: 'Manisha', gender: 'F', father: 'Surender Kumar', hindi: 92, english: 89, polSci: '99D', geography: '98D', sociology: '88D', total: 466, percent: 93.2, result: 'First Division' },
      { sNo: 15, roll: '3359330', name: 'Piyush', gender: 'M', father: 'Dharmveer', hindi: 75, english: 77, polSci: '88D', geography: '81D', sociology: 63, total: 384, percent: 76.8, result: 'First Division' },
      { sNo: 16, roll: '3359331', name: 'Sanjay', gender: 'M', father: 'Krishan Lal', hindi: 64, english: 57, polSci: '87D', geography: 71, sociology: 62, total: 341, percent: 68.2, result: 'First Division' },
      { sNo: 17, roll: '3359332', name: 'Sumit', gender: 'M', father: 'Shrif', hindi: 72, english: 61, polSci: '98D', geography: 73, sociology: 67, total: 371, percent: 74.2, result: 'First Division' },
      { sNo: 18, roll: '3359333', name: 'Tushar', gender: 'M', father: 'Brij Lal', hindi: 75, english: 60, polSci: '98D', geography: '80D', sociology: '77D', total: 390, percent: 78.0, result: 'First Division' },
      { sNo: 19, roll: '3359334', name: 'Yogita', gender: 'F', father: 'Fakir Chand', hindi: 72, english: 58, polSci: '76D', geography: 64, sociology: 63, total: 333, percent: 66.6, result: 'First Division' },
      { sNo: 20, roll: '3359335', name: 'Yogita', gender: 'F', father: 'Sahabram', hindi: 76, english: 59, polSci: '89D', geography: '75D', sociology: 60, total: 359, percent: 71.8, result: 'First Division' }
    ]
  },
  gallery: [
    {
      id: 1,
      category: "campus",
      titleEn: "Grand Entrance Gate & GSSS 52 LNP Main Campus",
      titleHi: "मुख्य प्रवेश द्वार एवं विद्यालय परिसर (मांझूवास)",
      tagEn: "Main Entrance",
      tagHi: "मुख्य द्वार",
      image: "assets/images/campus/main-gate-building.jpg"
    },
    {
      id: 2,
      category: "campus",
      titleEn: "Administrative Block (प्रशासनिक प्रभाग) - Faculty & Student Council",
      titleHi: "प्रशासनिक प्रभाग - विद्यालय शिक्षक एवं छात्र परिषद",
      tagEn: "Admin Block",
      tagHi: "प्रशासनिक प्रभाग",
      image: "assets/images/campus/administrative-block-staff-students.jpg"
    },
    {
      id: 3,
      category: "sports",
      titleEn: "School Athletics, Kabbadi & Tournament Team with Physical Education Teacher",
      titleHi: "विद्यालय खेलकूद, एथलेटिक्स व कबड्डी टीम मय शारीरिक शिक्षक",
      tagEn: "Sports Team",
      tagHi: "खेलकूद टीम",
      image: "assets/images/events/school-sports-team.jpg"
    },
    {
      id: 4,
      category: "science",
      titleEn: "ICT Smart Computer Lab & Practical Digital Learning Session",
      titleHi: "आईसीटी कंप्यूटर लैब व डिजिटल क्लासरूम शिक्षण",
      tagEn: "Computer Lab",
      tagHi: "कंप्यूटर लैब",
      image: "assets/images/campus/ict-computer-lab.jpg"
    },
    {
      id: 5,
      category: "cultural",
      titleEn: "'Say No To Plastics' Environmental & Eco-Awareness Rally",
      titleHi: "'से नो टू प्लास्टिक' पर्यावरण व जन-जागरूकता अभियान",
      tagEn: "Eco Awareness",
      tagHi: "पर्यावरण जागरूकता",
      image: "assets/images/events/say-no-to-plastic-rally.jpg"
    },
    {
      id: 6,
      category: "cultural",
      titleEn: "Grand Annual Day & National Festival Gathering under Canopy",
      titleHi: "भव्य वार्षिक उत्सव एवं राष्ट्रीय पर्व समारोह",
      tagEn: "Annual Function",
      tagHi: "वार्षिकोत्सव",
      image: "assets/images/events/annual-day-cultural-fest.jpg"
    },
    {
      id: 7,
      category: "cultural",
      titleEn: "Morning Prayer Assembly (सर्वधर्म प्रार्थना सभा) & Yoga Session",
      titleHi: "सर्वधर्म प्रार्थना सभा एवं योग/ध्यान सत्र",
      tagEn: "Morning Assembly",
      tagHi: "प्रार्थना सभा",
      image: "assets/images/events/morning-prayer-assembly.jpg"
    },
    {
      id: 8,
      category: "cultural",
      titleEn: "National Tricolor Flag Day & Cultural Celebration by Teachers & Students",
      titleHi: "राष्ट्रीय ध्वज तिरंगा उत्सव एवं सांस्कृतिक समारोह",
      tagEn: "National Festival",
      tagHi: "राष्ट्रीय पर्व",
      image: "assets/images/events/national-flag-celebration.jpg"
    },
    {
      id: 9,
      category: "campus",
      titleEn: "Eco-Club Tree Plantation Campaign by Girl Students",
      titleHi: "इको-क्लब हरियालो राजस्थान बालिका वृक्षारोपण अभियान",
      tagEn: "Eco Club",
      tagHi: "इको क्लब",
      image: "assets/images/events/tree-plantation-girls-group.jpg"
    },
    {
      id: 10,
      category: "campus",
      titleEn: "Boy Students Environmental Awareness & Tree Plantation Drive",
      titleHi: "पर्यावरण चेतना एवं छात्र पौधरोपण अभियान",
      tagEn: "Tree Plantation",
      tagHi: "वृक्षारोपण",
      image: "assets/images/events/boys-tree-plantation-drive.jpg"
    },
    {
      id: 11,
      category: "campus",
      titleEn: "Open-Air Courtyard Student Assembly & Mentorship Session",
      titleHi: "खुले प्रांगण में विद्यार्थी सभा एवं मार्गदर्शन सत्र",
      tagEn: "Student Assembly",
      tagHi: "विद्यार्थी सभा",
      image: "assets/images/events/courtyard-assembly-session.jpg"
    },
    {
      id: 12,
      category: "campus",
      titleEn: "Lush Green School Grounds & Heritage Banyan Tree Landscape",
      titleHi: "विशाल हरित विद्यालय प्रांगण एवं प्राचीन बरगद वृक्ष",
      tagEn: "Green Campus",
      tagHi: "हरित परिसर",
      image: "assets/images/campus/campus-panoramic.jpg"
    }
  ]
};
